import streamlit as st

"""
### This is the first page (`example_one.py`), loaded by default (because it's the first st.page in streamlit_app.py)

Note that the pages list in the sidebar is generated by the following code in streamlit_app.py:

```python
st.page("example_one.py", name="Home!", icon="🍔")

st.page("example_four.py", icon="🦊")

st.page("example_three.py", name="Custom name!", icon="🔥")

st.page("example_two.py", icon="⭐")

st.page(function_example, icon="🌊")
```

And the common elements are generated by the following code:

```python
st.sidebar.write("Common sidebar element")

"# Common header!"
```

The rest of the code in these pages is from the individual python files
or the function code.
"""
